### ISSUE TITLE
Precommit script broken

### ISSUE THREAD

**Issue by ponychicken** [bringbackourneighbours/bringbackourneighbours#12]
```
:root {
    --color-primary: #0b3e9c;
    --color-secondary: #e82b09;
    --color-background: #fff;
    --color-background-alt: #f5efe1;
}

body {
    font-family: 'FiraGO', sans-serif;
    background: var(--color-background-alt);
    margin: 0;
}
```
The pre-commit script throws some obscure error on this:
```
✖ stylelint --fix /home/xyz/CCM/bringbackourneighbours/src/base.css /home/xyz/CCM/bringbackourneighbours/src/components/Block.astro /home/xyz/CCM/bringbackourneighbours/src/components/WipHeader.astro /home/xyz/CCM/bringbackourneighbours/src/layouts/BaseLayout.astro:
SyntaxError: /home/xyz/CCM/bringbackourneighbours/node_modules/mdn-data/css/properties.json: Unterminated string in JSON at position 112878
    at parse (<anonymous>)
    at Module._extensions..json (node:internal/modules/cjs/loader:1445:39)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at file:///home/xyz/CCM/bringbackourneighbours/node_modules/css-tree/lib/data.js:6:23
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async normalizeAllRuleSettings (file:///home/xyz/CCM/bringbackourneighbours/node_modules/stylelint/lib/normalizeAllRuleSettings.mjs:17:16)

```

The CSS looks fine to me & i confirmed with W3C validator.

**Comment by jvoigt** [comment]
ah weird. it looks like stylint is tring to lint `node_modules/mdn-data/css/properties.json` 
so if think this either means that the file was staged by mistake ( it should be git-igored) or that we made a mistake in the filter for the linting

**Comment by jvoigt** [comment]
can you commit your changes to a different brach with `git commit --no-verify` so i can have a look.

**Comment by ponychicken** [comment]
Ya, the PR I have committed with no-verify

**Comment by ponychicken** [comment]
That JSON Was definitely not staged

**Comment by ponychicken** [comment]
I have disabled it for now.

**Comment by ponychicken** [comment]
I would suggest moving to CI anyway for this. It gives stronger assurances, and doesn't impeded workflow (its async)
