### ISSUE TITLE
Content: Flyer Bleiberecht de + en

### ISSUE THREAD

**Issue by jvoigt** [bringbackourneighbours/bringbackourneighbours#122]

**Comment by jvoigt** [comment]
Biem Build gibt es ne fehler meldung:

```
❯ npm run build

> bringbackourneighbours@0.0.1 build
> astro check && astro build

18:19:55 [types] Added src/env.d.ts type declarations.
18:19:55 [vite] Re-optimizing dependencies because vite config has changed
18:19:56 [types] Added src/env.d.ts type declarations.
18:19:56 Types generated 481ms
18:19:56 [check] Getting diagnostics for Astro files in /home/j.voigt/Workspace/bbon/bringbackourneighbours...
src/pages/[lang]/flyer/[identifier]/index.astro:14:7 - warning ts(6133): 'url' is declared but its value is never read.

14 const url = await getCanonicalUrlToFlyer(
         ~~~

src/pages/[lang]/kit/[identifier]/index.astro:14:7 - warning ts(6133): 'url' is declared but its value is never read.

14 const url = await getCanonicalUrlToKit(
         ~~~

src/pages/[lang]/page/[identifier]/index.astro:18:7 - warning ts(6133): 'url' is declared but its value is never read.

18 const url = await getCanonicalUrlToPage(
         ~~~

src/pages/link/[slug].astro:17:7 - warning ts(6133): 'target' is declared but its value is never read.

17 const target = entries.find((entry) => entry.slug === Astro.props.slug);
         ~~~~~~

src/util/redirect-not-found-or-not-translated.ts:9:3 - warning ts(6133): 'collection' is declared but its value is never read.

9   collection: T,
    ~~~~~~~~~~

Result (56 files): 
- 0 errors
- 0 warnings
- 5 hints

18:20:03 [types] Added src/env.d.ts type declarations.
18:20:03 [vite] Re-optimizing dependencies because vite config has changed
18:20:03 [types] Added src/env.d.ts type declarations.
18:20:03 [build] output: "static"
18:20:03 [build] directory: /home/j.voigt/Workspace/bbon/bringbackourneighbours/dist/
18:20:03 [build] Collecting build info...
18:20:03 [build] ✓ Completed in 412ms.
18:20:03 [build] Building static entrypoints...
18:20:03 [types] Added src/env.d.ts type declarations.
18:20:05 [vite] ✓ built in 2.22s
18:20:05 [build] ✓ Completed in 2.26s.

 building client (vite) 
18:20:05 [types] Added src/env.d.ts type declarations.
18:20:05 [vite] ✓ 5 modules transformed.
18:20:05 [vite] ✓ built in 11ms

 generating static routes 
18:20:05 ▶ src/pages/internal-print/flyer-[lang]-[identifier].astro
18:20:05   ├─ /internal-print/flyer-ar-detention/index.html (+26ms)
18:20:05   ├─ /internal-print/flyer-de-detention/index.html (+8ms)
18:20:05   ├─ /internal-print/flyer-en-detention/index.html (+7ms)
18:20:05   ├─ /internal-print/flyer-fr-detention/index.html (+7ms)
18:20:05   └─ /internal-print/flyer-en-residence/index.html (+8ms)
18:20:05 ▶ src/pages/internal-print/kit-[lang]-[identifier].astro
18:20:05   ├─ /internal-print/kit-ar-affected/index.html (+4ms)
18:20:05   ├─ /internal-print/kit-de-affected/index.html (+3ms)
18:20:05   └─ /internal-print/kit-en-affected/index.html (+4ms)
18:20:05 ▶ src/pages/link/[slug].astro
18:20:05   ├─ /link/asyleng/index.html (+2ms)
18:20:05   ├─ /link/asyldt/index.html (+1ms)
18:20:05   ├─ /link/attest/index.html (+1ms)
18:20:05   ├─ /link/stay/index.html (+1ms)
18:20:05   ├─ /link/bleiben/index.html (+1ms)
18:20:05   ├─ /link/flyer-ar-detention/index.html (+1ms)
18:20:05   ├─ /link/flyer-de-detention/index.html (+1ms)
18:20:05   ├─ /link/flyer-en-detention/index.html (+1ms)
18:20:05   ├─ /link/flyer-fr-detention/index.html (+1ms)
18:20:05   ├─ /link/flyer-en-residence/index.html (+1ms)
18:20:05   ├─ /link/kit-ar-affected/index.html (+1ms)
18:20:05   ├─ /link/kit-de-affected/index.html (+1ms)
18:20:05   └─ /link/kit-en-affected/index.html (+1ms)
18:20:06 λ src/pages/print/flyer-[lang]-[identifier].pdf.ts
18:20:06   ├─ /print/flyer-ar-detention.pdf (+4.53s)
18:20:10   ├─ /print/flyer-de-detention.pdf (+3.92s)
18:20:14   ├─ /print/flyer-en-detention.pdf (+5.73s)
18:20:20   ├─ /print/flyer-fr-detention.pdf (+2.54s)
18:20:23   └─ /print/flyer-en-residence.pdf (+2.83s)
18:20:25 λ src/pages/print/kit-[lang]-[identifier].pdf.ts
18:20:25   ├─ /print/kit-ar-affected.pdf (+4.15s)
18:20:30   ├─ /print/kit-de-affected.pdf (+3.81s)
18:20:33   └─ /print/kit-en-affected.pdf (+3.03s)
18:20:36 ▶ src/pages/showcase.astro
18:20:36   └─ /showcase/index.htmlURL: https://www.npmjs.com/package/qrcode#todataurltext-options-cberror-url-1
qrCodeImage: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAYAAAA9zQYyAAAAAklEQVR4AewaftIAAAdYSURBVO3BQW4ERxLAQLKh/3+Ze81TAYMeyXZtRljEWpd4WOsiD2td5GGtizysdZGHtS7ysNZFHta6yMNaF3lY6yIPa13kYa2LPKx1kYe1LvKw1kUe1rrIDy9p/KWSSWMqmTROSiaNT5RMGlPJpHFSMmmclJxonJScaPylkjce1rrIw1oXeVjrIj98Wck3aZyUTBpTyaQxaUwlk8aJxhslk8ZU8k0lk8ZUclLyTRrf9LDWRR7WusjDWhf54ZdpfKLkjZJJYyqZNCaNqWTS+ITGVPKGxknJVPKbND5R8pse1rrIw1oXeVjrIj/8x2lMJScan9CYSiaNqWTS+ETJScmJxv+zh7Uu8rDWRR7WusgP/+dKTjQmjalk0vhNGlPJVHKicbOHtS7ysNZFHta6yA+/rOSfVPIJjZOSSeOkZNKYSk40ppITjalkKpk03ij5N3lY6yIPa13kYa2L/PBlGv8mGlPJpDGVTBqfKJk0ppJJYyr5hMZUMmlMJW9o/Js9rHWRh7Uu8rDWRSziP0xjKjnR+ETJpHFScqIxlUwaU8mkMZWcaJyU3ORhrYs8rHWRh7UuYhEvaEwln9CYSiaNN0omjankExonJScab5RMGlPJicZfKjnRmEreeFjrIg9rXeRhrYtYxBdpTCUnGlPJicZUcqJxUjJpTCVvaJyUTBr/pJJPaEwlJxpTyTc9rHWRh7Uu8rDWRX54SWMqmTTe0Pimkjc0ppJJ442SSeOkZNKYSiaNNzSmkkljKplKftPDWhd5WOsiD2tdxCJe0JhKJo2pZNKYSk40Tkq+SeONkknjEyVvaEwln9D4RMmkcVLyTQ9rXeRhrYs8rHWRH14q+U0aU8kbGlPJScmJxidKJo0Tjalk0phKTjSmkknjpOSbNKaSNx7WusjDWhd5WOsiFvGCxlQyaUwlJxpTyYnGScmJxknJpHFSMmlMJW9oTCWTxjeVnGiclEwaU8k3Pax1kYe1LvKw1kV+eKnkExqf0DgpOdE4KZk0PlEyaUwlb2i8UTJpnJRMGm9oTCW/6WGtizysdZGHtS7yw0saU8lUcqJxUnKicVLymzRONE5KJo03SiaNv1Qyafylh7Uu8rDWRR7WuohFvKDxRsmk8YmSSeOk5BMaU8knNE5KJo2Tkt+k8YmSSeONkjce1rrIw1oXeVjrIhbxgsZU8gmNqeREYyr5Jo2p5ERjKjnROCk50ZhKTjTeKJk0vqnkmx7WusjDWhd5WOsiFvGCxlTyhsZJyaQxlUwaJyVvaHyiZNL4J5V8k8ZJyW96WOsiD2td5GGti1jECxpTyW/SeKPkROOk5ETjpOREYyo50ZhKvknjpORE46Tkmx7WusjDWhd5WOsiP/wxjalk0vhEySc03tCYSj6hMZWcaJyUfELjN2mclPymh7Uu8rDWRR7WuohFvKBxUvIJjankRGMq+YTGVDJpfFPJicZUMmlMJZPGN5VMGiclJxpTyTc9rHWRh7Uu8rDWRX54qWTSeKNk0phKTjROSk403iiZNE403tA4KZk0fpPGSclveljrIg9rXeRhrYtYxBdpvFFyonFSMmlMJZ/QOCn5Jo2TkkljKnlDYyqZNE5KJo2p5Dc9rHWRh7Uu8rDWRX74YyWTxonGSclJyaQxlXyiZNKYSk40PlEyabyhMZWcaEwlJxqf0JhK3nhY6yIPa13kYa2L/PCSxknJGyWf0DgpOdH4RMmJxknJGyWTxic0TkpONE5KTkq+6WGtizysdZGHtS7yw0slJxpTyVQyaZyUfKJk0jgpOdGYSk5KJo2/VDJpTCVvlEwak8ZU8pse1rrIw1oXeVjrIhbxL6IxlZxonJRMGiclJxp/qeQNjU+UTBpTyaQxlUwaJyXf9LDWRR7WusjDWhf54SWNk5JJ4xMaU8k/qeREYyr5hMakMZVMGlPJVDJpnGicaLxR8pse1rrIw1oXeVjrIhbxH6bxm0omjZOSNzSmkknjjZJJYyr5hMZU8k96WOsiD2td5GGti/zwksZfKvlNJZPGScmkMZWcaHxTyaTxhsZU8m/2sNZFHta6yMNaF/nhy0q+SeOk5Js0ppI3NP7LSj6h8YmSb3pY6yIPa13kYa2L/PDLND5R8gmNk5ITjalk0jgpmUomjalk0nij5KTkExp/SWMqeeNhrYs8rHWRh7Uu8sN/XMmk8YmSSeOkZNKYSqaSSeOkZNL4SyWTxknJpDGVnGh808NaF3lY6yIPa13kh8uUfELjmzROSiaNSWMqmTRONE5KppJJ46TkpGTSmEqmkm96WOsiD2td5GGti1jECxpTyTdpTCUnGlPJpDGVTBonJScaU8knNKaSNzROSt7QmEomjZOSb3pY6yIPa13kYa2L/PBlGn9JYyo5KZk0TkomjankExrfpDGVTCWTxic0TkomjU9oTCVvPKx1kYe1LvKw1kUsYq1LPKx1kYe1LvKw1kUe1rrIw1oXeVjrIg9rXeRhrYs8rHWRh7Uu8rDWRR7WusjDWhd5WOsiD2td5H9ITL+FiBE5fwAAAABJRU5ErkJggg==
 (+64ms)
18:20:37 ▶ src/pages/[lang]/flyer/[identifier]/[seo].astro
18:20:37   ├─ /ar/flyer/detention/فترةالحجز في انتظار الترحيل/index.html (+6ms)
18:20:37   ├─ /de/flyer/detention/abschiebehaft/index.html (+6ms)
18:20:37   ├─ /en/flyer/detention/deportation-custody/index.html (+6ms)
18:20:37   ├─ /fr/flyer/detention/Rétention Administrative/index.html (+2ms)
18:20:37   └─ /en/flyer/residence/Chances of a right to stay%3F/index.html (+6ms)
18:20:37 ▶ src/pages/[lang]/flyer/[identifier]/index.astro
18:20:37   ├─ /ar/flyer/detention/index.html (+1ms)
18:20:37   ├─ /de/flyer/detention/index.html (+1ms)
18:20:37   ├─ /en/flyer/detention/index.html (+1ms)
18:20:37   ├─ /fr/flyer/detention/index.html (+1ms)
18:20:37   └─ /en/flyer/residence/index.html (+1ms)
18:20:37 ▶ src/pages/[lang]/flyer/index.astro
18:20:37   ├─ /ar/flyer/index.html (+5ms)
18:20:37   ├─ /en/flyer/index.html (+3ms)
18:20:37   ├─ /fr/flyer/index.html (+3ms)
18:20:37   ├─ /ka/flyer/index.html (+6ms)
18:20:37   ├─ /de/flyer/index.html (+5ms)
18:20:37   ├─ /es/flyer/index.html (+6ms)
18:20:37   └─ /ur/flyer/index.html (+7ms)
18:20:37 ▶ src/pages/[lang]/kit/[identifier]/[seo].astro
18:20:37   ├─ /ar/kit/affected/حقيبة الإسعافات الأولية ضد الترحيل للأشخاص المهددين بالترحيل/index.html (+11ms)
18:20:37   ├─ /de/kit/affected/notfallkoffer-gegen-abschiebungen-fuer-betroffene/index.html (+10ms)
18:20:37   └─ /en/kit/affected/emergency-kit-against-deportations-for-people-threatened-with-deportation/index.html (+11ms)
18:20:37 ▶ src/pages/[lang]/kit/[identifier]/index.astro
18:20:37   ├─ /ar/kit/affected/index.html (+3ms)
18:20:37   ├─ /de/kit/affected/index.html (+2ms)
18:20:37   └─ /en/kit/affected/index.html (+2ms)
18:20:37 ▶ src/pages/[lang]/kit/index.astro
18:20:37   ├─ /ar/kit/index.html (+15ms)
18:20:37   ├─ /en/kit/index.html (+10ms)
18:20:37   ├─ /fr/kit/index.html (+16ms)
18:20:37   ├─ /ka/kit/index.html (+17ms)
18:20:37   ├─ /de/kit/index.html (+22ms)
18:20:37   ├─ /es/kit/index.html (+21ms)
18:20:37   └─ /ur/kit/index.html (+24ms)
18:20:37 ▶ src/pages/[lang]/page/[identifier]/[seo].astro
18:20:37   ├─ /de/page/contacts/Kontakte zu Verantwortlichen & Unterstützer*innen/index.html (+42ms)
18:20:37   ├─ /en/page/contacts/Contacts to responsible persons & supporters/index.html (+8ms)
18:20:37   ├─ /de/page/forms/Vorlagen zum Ausdrucken/index.html (+5ms)
18:20:37   ├─ /de/page/imprint/impressum-und-Datenschutz/index.html (+9ms)
18:20:37   ├─ /de/page/material/Material-zum-Ausdrucken/index.html (+7ms)
18:20:37   └─ /de/page/publicity/Öffentlichkeit schaffen und Unterstützung gewinnen/index.html (+8ms)
18:20:37 ▶ src/pages/[lang]/page/[identifier]/index.astro
18:20:37   ├─ /de/page/contacts/index.html (+1ms)
18:20:37   ├─ /en/page/contacts/index.html (+1ms)
18:20:37   ├─ /de/page/forms/index.html (+1ms)
18:20:37   ├─ /de/page/imprint/index.html (+1ms)
18:20:37   ├─ /de/page/material/index.html (+1ms)
18:20:37   └─ /de/page/publicity/index.html (+1ms)
18:20:37 ▶ src/pages/[lang]/wizard.astro
18:20:37   ├─ /ar/wizard/index.html (+8ms)
18:20:37   ├─ /en/wizard/index.html (+5ms)
18:20:37   ├─ /fr/wizard/index.html (+4ms)
18:20:37   ├─ /ka/wizard/index.html (+3ms)
18:20:37   ├─ /de/wizard/index.html (+3ms)
18:20:37   ├─ /es/wizard/index.html (+4ms)
18:20:37   └─ /ur/wizard/index.html (+5ms)
18:20:37 ▶ src/pages/[lang]/index.astro
18:20:37   ├─ /ar/index.html (+9ms)
18:20:37   ├─ /en/index.html (+4ms)
18:20:37   ├─ /fr/index.html (+4ms)
18:20:37   ├─ /ka/index.html (+4ms)
18:20:37   ├─ /de/index.html (+3ms)
18:20:37   ├─ /es/index.html (+4ms)
18:20:37   └─ /ur/index.html (+7ms)
18:20:37 ▶ src/pages/index.astro
18:20:37   └─ /index.html (+4ms)
18:20:37 ✓ Completed in 31.69s.

ENOENT: no such file or directory, stat '/home/j.voigt/Workspace/bbon/bringbackourneighbours/dist/en/flyer/residence/Chances of a right to stay'
  Stack trace:
    at Object.statSync (node:fs:1658:25)
    at file:///home/j.voigt/Workspace/bbon/bringbackourneighbours/node_modules/astro/dist/core/fs/index.js:17:7
    at removeEmptyDirs (file:///home/j.voigt/Workspace/bbon/bringbackourneighbours/node_modules/astro/dist/core/fs/index.js:15:11)
    at Array.map (<anonymous>)
    at file:///home/j.voigt/Workspace/bbon/bringbackourneighbours/node_modules/astro/dist/core/fs/index.js:17:7

```

**Comment by jvoigt** [comment]
German is still missing
